### ISSUE TITLE
advice and wish

### ISSUE THREAD

**Issue by e-v-medvedev** [colinmollenhour/magento-lite#25]
I think, You should add Customer module. It`s very usefull for many purposes. And magentoconnect in admin of course (imagine how easy to create a simple blog, installing aw_blog on magento lite :-)) . And we`ll wait Magento Lite, based on Magento 2.0. Thanks a lot for your job.

**Comment by colinmollenhour** [comment]
I am happy to consider pull requests. :)  However, I expect Mage_Customer will require significant work to rid it of dependencies to other modules like sales and catalog. Also if someone were to need customers but not catalog then I would guess that they would have lots of customer modifications in mind anyway and they might not want customer to be part of a third-party repo. That's just my take though and like I said I would be happy to consider a pull request which adds customer assuming it is tested enough to show that it works.

Regarding Magento 2, I hope that it doesn't even need such a fork to work as a "lite" version and simply disabling unwanted modules would be sufficient. Anyway, as I don't currently have a need for a "Mage 2 Lite" I don't expect to be tackling this anytime soon.
