### ISSUE TITLE
File List File Members app/code/core/Mage/Core/Model/App/Area.php

### ISSUE THREAD

**Issue by jiangwei1995** [colinmollenhour/magento-lite#26]
app/code/core/Mage/Core/Model/App/Area.php   92line
  $this->_loadPart(self::PART_CONFIG)
                ->_loadPart(self::PART_EVENTS)
                ->_loadPart(self::PART_DESIGN)
                ->_loadPart(self::PART_TRANSLATE);

What meaning

**Comment by colinmollenhour** [comment]
I'm afraid if you want a good answer you're going to have to be a bit more precise with your question.

**Comment by jiangwei1995** [comment]
I do performance testing found
These four are not loaded , improve performance

**Comment by jiangwei1995** [comment]
I do performance testing found
These four are not loaded , improve performance

**Comment by jiangwei1995** [comment]
@colinmollenhour 
I do performance testing found
These four are not loaded , improve performance

**Comment by colinmollenhour** [comment]
This project is currently only for tracking the latest Magento with the minimal changes required to get a working result and it does not try to add improvement or optimizations. As config, events, design and translate are all relevant to the subset of Magento features kept in this release, I think removing them should be up to the user which the user can do with a rewrite or overload. Thanks!
