### ISSUE TITLE
Full URL redirection

### ISSUE THREAD

**Issue by hfcandeias** [colinmollenhour/magento-lite#27]
Hey,

Thx for sharing this. Apparently mod_rewrite is not redirecting the full url for me when ssl enabled through a load balancer. If I type domain.com/page it loops back to https://domain.com
I tried to change the rewrites rules but breaks my /pages. Would you kindly help out?

Thx in advance.

**Comment by colinmollenhour** [comment]
Sorry, unfortunately I don't have time to help with issues unless it is an actual bug. I suggest the Magento Stack Exchange as the place to go for help with this type of issue.

http://magento.stackexchange.com/
