### ISSUE TITLE
Warning: include(Zend/Cache.php): failed to open stream: No such file or directory in lib/Varien/Autoload.php on line 94

### ISSUE THREAD

**Issue by progammer-rkt** [colinmollenhour/magento-lite#28]
I got this error while installing Magento lite instance. 
> Warning: include(Zend/Cache.php): failed to open stream: No such file or directory in lib/Varien/Autoload.php on line 94

How can I resolve this Issue ?

**Comment by progammer-rkt** [comment]
This is because Zend Libraries are absent in `lib/Zend` directory. To resolve this issue, you can copy all Zend libraries from a normal Magento instance and place under `lib/Zend` directory.

**Comment by colinmollenhour** [comment]
This is covered by the README under Installation:

https://github.com/colinmollenhour/magento-lite#installation
