### ISSUE TITLE
Unable to delete store view

### ISSUE THREAD

**Issue by wlcheck** [colinmollenhour/magento-lite#7]
It is not possible to delete store view after creation, there are some issues regarding indexing.

**Comment by prateektechno** [comment]
There are calls to index module in store models delete related functions _beforeDelete() and _afterDeleteCommit(). Removing these will get the functionality to work. Can they be migrated to the community code pool?

**Comment by colinmollenhour** [comment]
For now I am keeping magento-lite strictly dedicated to making core functionality working with minimal modifications. I suggest submitting the fix to Magento core team (perhaps via magento2 repo) and maintaining your own branch or fork with bug fixes and improvements in the meantime.
